#!/usr/bin/env python3
"""Offline encoder model for history-lesson.  Reports SYMBOL COUNT and box only.

Improvements over build_ring.py's greedy encoder, each measurable on its own:
  * base 100 instead of 92 -- B^9 <= 10^18 still holds at B=100, so a slot of 18
    digits still carries 9 symbols, but the alphabet gains 8 free direct slots;
  * the raw byte range is remapped onto the bytes the text ACTUALLY uses (71 of
    them) instead of a fixed ASCII window, freeing ~20 more direct slots;
  * direct/escape assignment is chosen by profit, not by a fixed split, so a
    rare literal byte can be demoted to an escape to make room for a hot phrase;
  * the parse is a shortest path, not greedy.
"""
import collections, heapq, math, sys

sys.path.insert(0, "/Users/visenbaev/icfpc26/scratchpad/hist")
import geom2

TXT = "/Users/visenbaev/icfpc26/solutions/history-lesson/icfp-history.txt"
DATA = open(TXT, "rb").read()

# ---- the year prefixes are generated by a counter in the decoder ------------
YEARS = [b"; %d: " % y for y in range(1997, 2027)]


def split_years(data):
    """Return the text with each '; YYYY: ' prefix replaced by \x00."""
    out = bytearray()
    i = 0
    hits = 0
    while i < len(data):
        for p in YEARS:
            if data.startswith(p, i):
                out.append(0)
                i += len(p)
                hits += 1
                break
        else:
            out.append(data[i])
            i += 1
    return bytes(out), hits


BODY, NYEAR = split_years(DATA)


# ---- phrase candidate generation -------------------------------------------
def candidates(body, maxlen=12, minlen=2, top=4000):
    cnt = collections.Counter()
    for L in range(minlen, maxlen + 1):
        for i in range(len(body) - L + 1):
            s = body[i:i + L]
            if 0 in s:
                continue
            cnt[s] += 1
    return [s for s, c in cnt.items() if c >= 2][:200000]


def parse_cost(body, direct, escaped):
    """Shortest path: cost 1 per direct token, 2 per escaped token."""
    n = len(body)
    INF = float("inf")
    best = [INF] * (n + 1)
    best[0] = 0
    by_first = collections.defaultdict(list)
    for s, c in list(direct.items()) + list(escaped.items()):
        by_first[s[0]].append((s, c))
    for i in range(n):
        if best[i] == INF:
            continue
        for s, c in by_first.get(body[i], ()):
            j = i + len(s)
            if j <= n and body[i:j] == s and best[i] + c < best[j]:
                best[j] = best[i] + c
    return best[n]


def evaluate(base=100, maxphrase=9, verbose=False):
    body = BODY
    used = sorted(set(body))                     # includes 0 (the year token)
    # every single byte must be encodable
    singles = {bytes([b]): 1 for b in used}

    # candidate phrases
    cnt = collections.Counter()
    for L in range(2, maxphrase + 1):
        for i in range(len(body) - L + 1):
            s = body[i:i + L]
            if 0 in s:
                continue
            cnt[s] += 1
    cands = [s for s, c in cnt.items() if c >= 2]

    # slot budget: base symbols, one reserved as the escape marker
    ndirect = base - 1
    nesc = base

    # greedy: score each token by (uses saved) and iterate a few rounds
    tokens = {bytes([b]): 0 for b in used}
    tokens.update({s: 0 for s in cands})

    # start from singles only, then add phrases by measured marginal gain
    chosen = list(singles)
    for _ in range(6):
        direct, escaped = assign(chosen, body, ndirect, nesc)
        base_cost = parse_cost(body, direct, escaped)
        gains = []
        for s in cands:
            if s in direct or s in escaped:
                continue
            gains.append((cnt[s] * (len(s) - 1), s))
        gains.sort(reverse=True)
        added = 0
        for _, s in gains[:400]:
            if len(chosen) >= ndirect + nesc:
                break
            chosen.append(s)
            added += 1
        if not added:
            break
    direct, escaped = assign(chosen, body, ndirect, nesc)
    syms = parse_cost(body, direct, escaped)
    return syms, direct, escaped


def assign(chosen, body, ndirect, nesc):
    """Split the chosen tokens into direct (1 sym) and escaped (2 syms) by the
    measured usage of a direct-everything parse."""
    trial_direct = {s: 1 for s in chosen}
    n = len(body)
    INF = float("inf")
    best = [INF] * (n + 1)
    prev = [None] * (n + 1)
    best[0] = 0
    by_first = collections.defaultdict(list)
    for s in chosen:
        by_first[s[0]].append(s)
    for i in range(n):
        if best[i] == INF:
            continue
        for s in by_first.get(body[i], ()):
            j = i + len(s)
            if j <= n and body[i:j] == s and best[i] + 1 < best[j]:
                best[j] = best[i] + 1
                prev[j] = s
    use = collections.Counter()
    j = n
    while j:
        s = prev[j]
        use[s] += 1
        j -= len(s)
    # profit of a direct slot = uses (each escaped use costs 1 extra symbol)
    ranked = sorted(chosen, key=lambda s: -use[s])
    direct = {s: 1 for s in ranked[:ndirect]}
    escaped = {s: 2 for s in ranked[ndirect:ndirect + nesc]}
    # every single byte must remain encodable somewhere
    for s in chosen:
        if len(s) == 1 and s not in direct and s not in escaped:
            escaped[s] = 2
    return direct, escaped


if __name__ == "__main__":
    print(f"text {len(DATA)} B -> body {len(BODY)} tokens "
          f"({NYEAR} year prefixes folded)")
    for base in (92, 100):
        syms, direct, escaped = evaluate(base=base)
        # preload cells: each phrase (len>1) packed base-128 -> decimal literal
        pre = 0
        for s in list(direct) + list(escaped):
            if len(s) > 1:
                v = int.from_bytes(s, "little")
                pre += len(str(v)) + 3
        prerows = math.ceil(pre / 76)
        r = geom2.solve(syms, dec_rows=9 + prerows)[0]
        print(f"base {base}: syms={syms} phrases={sum(1 for s in list(direct)+list(escaped) if len(s)>1)}"
              f" preload={pre} cells ({prerows} rows) -> box {r[0]} ({r[1]}x{r[2]})")
