#!/usr/bin/env python3
"""Can YEAR lose row 2 now that --year-pad=1 gives it a 28th column?  NO.

YEAR's 27x5 interior, traced from build_ring.year_rows():

  row0  @ `d_init(17)` M `10` b v          full, x=0..26
  row1  v _ _ < ................ < _ _ <   blanks at 1,2,4..22,24,25
  row2  _ _ _ s ...................        blank except the lone `s` at x=3
  row3  v _ _ N b `01` M + N `d_corr` <    blanks at 1,2 only
  row4  > r N X W s M `d_step` + M m a _ _ ^   blanks at 24,25

Four routes:
  init     (26,0)v -> (26,1)< west to (0,1)v -> south -> (0,4)> east
  X<0      (3,4)X ccw N -> (3,3)N -> (3,2)s -> (3,1)< west to (0,1) -> south
  a/BP>0   (23,4)a ccw N -> (23,3) -> (23,2) -> (23,1)< west to (0,1)
  CORR     (26,4)^ -> (26,3)< west along row3 to (0,3)v

Deleting row 2 costs the X<0 route its `s`, so the send must move to a cell that
ONLY that route walks.  It cannot:
  * row 1 west of x=3 -- init enters row 1 at x=26 and a/BP>0 at x=23, and BOTH
    run west to x=0, so (0,1),(1,1),(2,1),(3,1) are all shared;
  * row 3 -- CORR runs west from x=25 to x=0, so (1,3),(2,3) are shared too;
  * row 0 -- full across all 27 columns.

The 28th column from --year-pad=1 is at x=27, the EAST end.  The X<0 route is
generated by the `X` at x=3 and never travels east of x=3, so a free cell at
x=27 is unreachable by it.  Moving the branch east is impossible as well: `X`
must follow `r`,`N` at x=1,2, and the rest of row 4 (W s M `d_step` + M m a)
needs 20 more columns east of it.

MEASURED DEAD: the freed column is at the wrong end of the room.  It would take
a YEAR rewrite that re-enters row 4 from the east, not a placement change.
