"""Emit a standalone, regenerable builder for a produced 12x12 .man."""
import sys, os
man = sys.argv[1]; out = sys.argv[2]
rows = open(man).read().split('\n')
W = max(len(r) for r in rows); H = len([r for r in rows if r.strip()])
def at(x, y):
    if 0 <= y < len(rows) and 0 <= x < len(rows[y]): return rows[y][x]
    return ' '
claimed = set(); rooms = []
for y0 in range(H):
    for x0 in range(W):
        if at(x0, y0) != '+': continue
        x1 = x0 + 1
        while at(x1, y0) == '-': x1 += 1
        if x1 <= x0 + 1 or at(x1, y0) != '+': continue
        y1 = y0 + 1
        while at(x0, y1) == '|': y1 += 1
        if y1 <= y0 + 1 or at(x0, y1) != '+': continue
        if at(x1, y1) != '+': continue
        if not (all(at(x, y1) == '-' for x in range(x0 + 1, x1))
                and all(at(x1, y) == '|' for y in range(y0 + 1, y1))): continue
        per = {(x, y0) for x in range(x0, x1 + 1)} | {(x, y1) for x in range(x0, x1 + 1)} \
              | {(x0, y) for y in range(y0, y1 + 1)} | {(x1, y) for y in range(y0, y1 + 1)}
        if per & claimed: continue
        claimed |= per; rooms.append((x0, y0, x1, y1))
inroom = set()
for (x0, y0, x1, y1) in rooms:
    for x in range(x0, x1 + 1):
        for y in range(y0, y1 + 1): inroom.add((x, y))
ARR = {'>': (1, 0), '<': (-1, 0), 'v': (0, 1), '^': (0, -1)}
def border(p):
    for i, (x0, y0, x1, y1) in enumerate(rooms):
        if x0 <= p[0] <= x1 and y0 <= p[1] <= y1 and (p[0] in (x0, x1) or p[1] in (y0, y1)):
            return i
    return None
pipes = []
used = set()
for y in range(H):
    for x in range(W):
        c = at(x, y)
        if c not in ARR or (x, y) in inroom or (x, y) in used: continue
        d = ARR[c]
        if border((x - d[0], y - d[1])) is None: continue
        path = [(x, y)]; pos = (x, y); dr = d
        while True:
            nx = (pos[0] + dr[0], pos[1] + dr[1])
            if border(nx) is not None: break
            path.append(nx); pos = nx
            if at(nx[0], nx[1]) in ARR: dr = ARR[at(nx[0], nx[1])]
        used |= set(path)
        pipes.append(path)
# interior op cells (non-room, non-pipe) grouped by room
ops = {}
for i, (x0, y0, x1, y1) in enumerate(rooms):
    cells = {}
    for x in range(x0 + 1, x1):
        for y in range(y0 + 1, y1):
            if at(x, y) != ' ': cells[(x, y)] = at(x, y)
    ops[i] = cells
body = ['#!/usr/bin/env python3',
        '"""sort-numbers 12x12 (box 144) -- generated by scratchpad/sort12/drive5.py.',
        '',
        'Main room interior is 8x5 (see scratchpad/sort12/main5.py for the control flow).',
        'The geometry below is what the exhaustive floorplan search settled on: the',
        'main->relay pipe is short (q reads the circulating count only ~11 ticks after',
        'the last send) and the relay->main return pipe holds the 15 values that lap 1',
        'puts into circulation.',
        '"""', 'import os', 'import sys', '',
        'W = H = %d' % max(W, H), 'g = [[" "] * W for _ in range(H)]', '',
        'def put(x, y, ch):',
        '    if g[y][x] != " ":',
        '        raise SystemExit("collision at (%d,%d)" % (x, y))',
        '    g[y][x] = ch', '',
        'def room(x0, y0, x1, y1):',
        '    for x in range(x0, x1 + 1):',
        '        put(x, y0, "-" if x0 < x < x1 else "+")',
        '        put(x, y1, "-" if x0 < x < x1 else "+")',
        '    for y in range(y0 + 1, y1):',
        '        put(x0, y, "|"); put(x1, y, "|")', '',
        'ROOMS = %r' % (rooms,),
        'CELLS = %r' % ([sorted(ops[i].items()) for i in range(len(rooms))],),
        'PIPES = %r' % (pipes,), '',
        'for r in ROOMS:', '    room(*r)',
        'for grp in CELLS:', '    for (x, y), ch in grp:', '        put(x, y, ch)',
        'ARR = {(1, 0): ">", (-1, 0): "<", (0, 1): "v", (0, -1): "^"}',
        'for p in PIPES:',
        '    for i, c in enumerate(p):',
        '        n = p[i + 1] if i + 1 < len(p) else None',
        '        if n is None:',
        '            d = LAST[tuple(map(tuple, [p[0], p[-1]]))] if False else None',
        '        put(c[0], c[1], "?")', '']
open(out, 'w').write('\n'.join(body))
print('rooms', rooms)
print('pipes', [(p[0], p[-1], len(p)) for p in pipes])
